- name: install nginx
  hosts: web
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: starts nginx
      ansible.builtin.yum:
        name: nginx
        start: started
        enabled: yes
