- name: demo on conditions
  hosts: all
  connection: local
  tasks:
    - name: name of the fruit
      ansible.builtin.debug:
        msg: fruit = apple


    - name: name of the vegetable
      ansible.builtin.debug:
        msg: vegetable = carrot


